vision_assistant_path_config:
  process_library_path: "/home/pmlab/pm_Server/01_PM_Zelle/03_PM_DataBase/Vision/vision_processes/"
  vision_database_path: "/home/pmlab/pm_Server/01_PM_Zelle/03_PM_DataBase/Vision/vision_image_db/"
  camera_config_path: "/home/pmlab/pm_Server/01_PM_Zelle/03_PM_DataBase/Vision/vision_camera_configs/"
  vision_assistant_config: "/home/pmlab/pm_ros2_ws/src/pm_vision/config/vision_assistant_config.yaml"

