vision_assistant_config:
  cross_validation: False    #test
  show_image_on_error: False
  step_though_images: True
  image_display_time_in_execution_mode: 5
  scale_ouput_window_to_screen_size: True
  show_input_and_output_image: True
